config/routes.rb
Rails.application.routes.draw do
  # get 'tasks', to: 'tasks#index'
  # post 'tasks', to: 'tasks#create'
  # get 'tasks/new', to: 'tasks#new', as: :new_task
  # get 'tasks/:id', to: 'tasks#show', as: :task
  # get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  # patch 'tasks/:id', to: 'tasks#update'
  # delete 'tasks/:id', to: 'tasks#destroy'

  resources :tasks
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: [ :show, :edit, :update, :destroy ]

  def index
    @tasks = Task.all
  end

  def show
  end

  def new
    @task = Task.new
  end

  def create
    task = Task.new(task_params)
    task.save
    redirect_to tasks_path
  end

  def edit
  end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def set_task
    @task = Task.find(params[:id])
  end

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <div class="row">
        <div class="col-sm-6 col-sm-offset-3">
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for(@task) do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
  </div>

  <div class="form-group">
    <%= f.label :details %>
    <%= f.text_area :details, class: 'form-control' %>
  </div>

  <% unless f.object.new_record? %>
    <div class="checkbox">
      <label>
        <%= f.check_box :completed %> Completed
      </label>
    </div>
  <% end %>

  <%= f.submit class: 'btn btn-primary' %>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit task</h1>

<%= render 'form', task: @task %>

<hr>
<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/tasks/index.html.erb
<h1>My tasks</h1>

<ul id="tasks">
  <% @tasks.each do |task| %>
    <li>
      <% if task.completed %>
        <i class="fa fa-check-square-o"></i>
      <% else %>
        <i class="fa fa-square-o"></i>
      <% end %>
      <%= link_to task.title, task_path(task.id) %>
      ·
      <%= link_to task_path(task.id), method: :delete, data: { confirm: "Delete #{task.title}?" } do %>
        <i class="fa fa-trash-o" aria-hidden="true"></i>
      <% end %>
    </li>
  <% end %>
</ul>

<hr>

<%= link_to new_task_path do %>
  <i class="fa fa-plus"></i> Add a new task
<% end %>

app/views/tasks/new.html.erb
<h1>New task</h1>

<%= render 'form', task: @task %>

<hr>
<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>

app/views/tasks/show.html.erb
<%= link_to edit_task_path(@task.id), class: 'pull-right btn btn-default' do %>
  <i class="fa fa-pencil"></i> Edit this task
<% end %>

<h1><%= @task.title %></h1>

<p class="well"><%= @task.details %></p>

<% if @task.completed %>
  <i class="fa fa-check-square-o"></i> This task is completed
<% else %>
  <i class="fa fa-square-o"></i> This task is not completed yet
<% end %>

<hr>
<%= link_to tasks_path do %>
  <i class="fa fa-history"></i> Back to list
<% end %>